import { Product, Review } from './types';

// Exporting generated image assets
export const IMAGES = {
  heroBanner: 'https://files.catbox.moe/x1u36m.jpg',
  cosmeticsHero: 'https://files.catbox.moe/zoxoiy.jpg',
  fashionHero: 'https://files.catbox.moe/fzwuhg.jpg',
  familyBrand: 'https://files.catbox.moe/l5gofz.jpg',
  lipstickTint: '/src/assets/images/lipstick_tint_1781081319860.png',
  lotusCream: '/src/assets/images/lotus_cream_1781081334866.png',
  georgetteFrock: '/src/assets/images/georgette_frock_1781081350941.png',
  anarkaliSuit: '/src/assets/images/anarkali_suit_1781081367092.png',
  crimsonSaree: '/src/assets/images/crimson_saree_1781590471704.jpg',
  saffronCream: '/src/assets/images/saffron_cream_1781590490066.jpg',
  silkKurta: '/src/assets/images/silk_kurta_1781590508237.jpg',
};

export const PRODUCTS: Product[] = [
  // COSMETICS / SKINCARE
  {
    id: 'cos-01',
    name: 'Vinshu Radiant Elixir Rose Serum',
    category: 'cosmetics',
    type: 'Skincare',
    price: 38.00,
    rating: 4.9,
    reviewsCount: 148,
    description: 'A luxurious, lightweight glowing elixir infused with cold-pressed organic rose extract, pure gold flakes, and botanical hyaluronic acid to instantly brighten, plump, and deeply hydrate your skin.',
    image:'https://files.catbox.moe/x5yy8o.jpg',
    badge: 'Bestseller',
    ingredients: ['Organic Rose Extract', '24k Gold Flakes', 'Hyaluronic Acid', 'Niacinamide (Vitamin B3)'],
    familyDemographic: 'Women',
    isFeatured: true
  },
  {
    id: 'cos-02',
    name: 'Aura Glow Dewy Lip & Cheek Tint',
    category: 'cosmetics',
    type: 'Makeup',
    price: 24.00,
    rating: 4.8,
    reviewsCount: 92,
    description: 'A versatile, buildable creamy tint containing organic peach pulp and nourishing shea butter. Provides a natural healthy flush of warm pink color for dynamic daily wear.',
    image: 'https://files.catbox.moe/gk135s.jpg',
    badge: 'New',
    colors: ['Sweet Rose', 'Vibrant Peach', 'Gold Sand'],
    ingredients: ['Peach Seed Oil', 'Shea Butter', 'Vitamin E', 'Organic Mineral Pigments'],
    familyDemographic: 'Women',
    isFeatured: true
  },
  {
    id: 'cos-03',
    name: 'Golden Lotus Wrinkle-Repair Cream',
    category: 'cosmetics',
    type: 'Skincare',
    price: 52.00,
    rating: 4.7,
    reviewsCount: 74,
    description: 'A rich, comforting age-defying cream infused with Golden Lotus stem cells, amino peptides, and cold-pressed squalane. Refines skin texture while restoring overnight suppleness.',
    image: 'https://files.catbox.moe/enz8g1.jpg',
    ingredients: ['Lotus Flower Extract', 'Micro-peptides', 'Eco-squalane', 'Rosehip Oil'],
    familyDemographic: 'Elders',
    isFeatured: false
  },
  {
    id: 'cos-04',
    name: 'Botanical Energizing Clay Face Polish',
    category: 'cosmetics',
    type: 'Skincare',
    price: 29.00,
    rating: 4.6,
    reviewsCount: 51,
    description: 'Deeply purifying fine clay facial polish infused with organic peppermint, tea tree oil, and bamboo micro-scrubbers. Perfect for refreshing daily skincare routines.',
    image: 'https://files.catbox.moe/a8i8yi.png',
    badge: 'Eco Friendly',
    ingredients: ['White Kaolin Clay', 'Peppermint Oil', 'Bamboo Micro-extracts', 'Aloe Vera Leaf Juice'],
    familyDemographic: 'Men',
    isFeatured: false
  },
  {
    id: 'cos-05',
    name: 'Vinshu Ultra-Gentle Oats Moisture Balm',
    category: 'cosmetics',
    type: 'Skincare',
    price: 19.00,
    rating: 4.9,
    reviewsCount: 110,
    description: 'An absolute savior for sensitive skins. Formulated with colloidal oats, chamomile floral water, and organic coconut wax. Designed to safely hydrate soft and dry barrier patches.',
    image: 'https://files.catbox.moe/7kqtby.jpg',
    ingredients: ['Colloidal Oat Flour', 'Chamomile Water', 'Organic Coconut Oil', 'Calendula Extract'],
    familyDemographic: 'Kids',
    isFeatured: true
  },

  // CLOTHING / APPAREL
  {
    id: 'clo-01',
    name: 'Sunset Garden Silk Wrap Dress',
    category: 'clothing',
    type: 'Apparel',
    price: 89.00,
    rating: 4.9,
    reviewsCount: 220,
    description: 'Bring bright, artistic elegance with you. Tailored in an exquisite mulberry silk blend featuring a hand-drawn floral design, adjustable gold-ring waist tie, and elegant balloon sleeves.',
    image: 'https://files.catbox.moe/l0rso6.png',
    badge: 'Bestseller',
    sizes: ['XS', 'S', 'M', 'L', 'XL','XXL'],
    colors: ['Rose Pink', 'Peach Nectar', 'Soft Lavender'],
    familyDemographic: 'Women',
    isFeatured: true
  },
  {
    id: 'clo-02',
    name: 'Golden Coast Tailored Linen Blazer',
    category: 'clothing',
    type: 'Apparel',
    price: 115.00,
    rating: 4.7,
    reviewsCount: 64,
    description: 'An unvarnished modern standard. Effortlessly structured using premium organic breathable French linen with subtle peach contrast lining, gold luxury buttons, and internal travel pockets.',
    image: 'https://files.catbox.moe/5topop.jpg',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Oatmeal', 'Soft Sage', 'Light Denim'],
    familyDemographic: 'Men',
    isFeatured: true
  },
  {
    id: 'clo-03',
    name: 'Kids Sweet Organic Cotton Overalls',
    category: 'clothing',
    type: 'Apparel',
    price: 34.00,
    rating: 4.8,
    reviewsCount: 88,
    description: 'Cute, chemical-free and incredibly durable. Woven from 100% GOTS-certified organic cotton, with adjustable button suspenders and snap closures for quick play adjustments.',
    image: 'https://files.catbox.moe/h1mfq8.png',
    badge: 'Eco Friendly',
    sizes: ['2T', '3T', '4T', '5-6Y'],
    colors: ['Blossom Pink', 'Peach Splash', 'Mint Sage'],
    familyDemographic: 'Kids',
    isFeatured: true
  },
  {
    id: 'clo-04',
    name: 'Luxe Cashmere Blend Meadow Cardigan',
    category: 'clothing',
    type: 'Apparel',
    price: 145.00,
    rating: 4.9,
    reviewsCount: 42,
    description: 'Wrap yourself in absolute warmth and prestige. This heavyweight meadow cardigan is constructed using Mongolian cashmere and superfine merino wool, featuring gorgeous hand-carved horn buttons and modern dropped shoulders.',
    image: 'https://files.catbox.moe/wggpvj.png',
    badge: 'Limited Edition',
    sizes: ['S', 'M', 'L', 'XL','XXL'],
    colors: ['Creamy Butter', 'Heather Lavender', 'Soft Rose'],
    familyDemographic: 'Elders',
    isFeatured: true
  },
  {
    id: 'clo-05',
    name: 'Casual Sunday Slub Cotton Tee',
    category: 'clothing',
    type: 'Apparel',
    price: 28.00,
    rating: 4.5,
    reviewsCount: 130,
    description: 'An upgraded wardrobe fundamental. Crafted from thick pre-shrunk premium slub cotton, displaying a charming uneven premium knit texture and custom reinforcement neck stitching.',
    image: 'https://files.catbox.moe/ppqkd9.png',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Sandstone', 'Rose Clay', 'Mist Blue'],
    familyDemographic: 'Men',
    isFeatured: false
  },
  {
    id: 'clo-06',
    name: 'Elders Classic Pleated Linen Trouser',
    category: 'clothing',
    type: 'Apparel',
    price: 68.00,
    rating: 4.8,
    reviewsCount: 39,
    description: 'Perfect ease of movement meets exquisite dressing. Designed with a flexible side-elasticated waist, pleated details, and breathable relaxed tailoring matching perfect casual style.',
    image: 'https://files.catbox.moe/3gp9nh.png',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Soft Off-White', 'Muted Gold', 'Desert Sand'],
    familyDemographic: 'Elders',
    isFeatured: false
  },
  {
    id: 'clo-07',
    name: 'Inaya Peach Georgette Flounced Frock',
    category: 'clothing',
    type: 'Apparel',
    price: 74.00,
    rating: 4.9,
    reviewsCount: 115,
    description: 'A charming, ultra-feminine, lightweight frock dress tailored from cloud-soft georgette fabric. Features fine layered ruffles, a synched ribbon waist, and micro-pleat details that dance beautifully.',
    image: 'https://files.catbox.moe/xkyhv8.jpg',
    badge: 'New',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Peach Silk', 'Blush Rose', 'Off-White'],
    familyDemographic: 'Women',
    isFeatured: true
  },
  {
    id: 'clo-08',
    name: 'Royale Heritage Embroidered Anarkali Suit',
    category: 'clothing',
    type: 'Apparel',
    price: 155.00,
    originalPrice: 299.00,
    rating: 4.9,
    reviewsCount: 84,
    stockCount: 3,
    vinshuAssured: true,
    description: 'An exceptional celebration of classical artistry. Beautifully tailored peach and rose-red georgette silhouette featuring grand imperial sweeps, intricate golden zari floral embroidery, and a matching hand-spun chiffon dupatta.',
    image: 'https://files.catbox.moe/ad0p26.jpg',
    badge: 'Limited Edition',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Empress Pink & Gold', 'Soft Peach & Ivory'],
    familyDemographic: 'Women',
    isFeatured: true
  },
  {
    id: 'clo-09',
    name: 'Royale CRFIMSON Georgette Bridal Saree',
    category: 'clothing',
    type: 'Apparel',
    price: 189.00,
    originalPrice: 350.00,
    rating: 4.9,
    reviewsCount: 167,
    stockCount: 4,
    vinshuAssured: true,
    description: 'An absolute masterpiece of craftsmanship. Beautifully draped georgette fabric in bold crimson red, displaying grand gold zari brocade borders and traditional floral buttis, comes with an unstitched blouse piece.',
    image: 'https://files.catbox.moe/5g0ixs.jpg',
    badge: 'Bestseller',
    sizes: ['Free Size (5.5m Saree)'],
    colors: ['Crimson Red & Gold', 'Soft Red & Copper Gold'],
    familyDemographic: 'Women',
    isFeatured: true
  },
  {
    id: 'cos-06',
    name: 'Kashmiri Saffron Royal Face Cream',
    category: 'cosmetics',
    type: 'Skincare',
    price: 49.00,
    originalPrice: 95.00,
    rating: 4.8,
    reviewsCount: 142,
    stockCount: 6,
    vinshuAssured: true,
    description: 'A genuine Ayurvedic skin rejuvenator. Combines premium hand-pulled Kashmiri saffron threads with royal sandalwood paste and whipped almond honey cream to visibly polish complexion and lock in moisture.',
    image: 'https://files.catbox.moe/u7v406.png',
    badge: 'New',
    ingredients: ['Kashmiri Saffron Threads', 'Pure Sandalwood Extract', 'Almond Milk Extract', 'Organic Forest Honey'],
    familyDemographic: 'Women',
    isFeatured: true
  },
  {
    id: 'clo-10',
    name: 'Chic Kids Premium Silk Kurta Pajama Set',
    category: 'clothing',
    type: 'Apparel',
    price: 45.00,
    originalPrice: 85.00,
    rating: 4.8,
    reviewsCount: 55,
    stockCount: 8,
    vinshuAssured: true,
    description: 'Super-comprehensive luxury ethnic wear. Cut from breathable raw silk and organic-cotton blends that are hypoallergenic and gentle on young skins. Includes a traditional churidar tight trouser.',
    image: 'https://files.catbox.moe/dnvwux.jpg',
    badge: 'New',
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-12Y'],
    colors: ['Peach Gold', 'Imperial Maroon', 'Mint Sage'],
    familyDemographic: 'Kids',
    isFeatured: true
  },
  {
    id: 'cos-07',
    name: 'Sandalwood Botanical Deep Cleansing Face Wash',
    category: 'cosmetics',
    type: 'Skincare',
    price: 22.00,
    originalPrice: 40.00,
    rating: 4.7,
    reviewsCount: 39,
    stockCount: 12,
    vinshuAssured: false,
    description: 'A deeply refreshing, non-drying foaming face wash blended with Indian red sandalwood wood juices, antibacterial neem seed extract, and organic wild honey.',
    image: 'https://files.catbox.moe/a8i8yi.png',
    ingredients: ['Red Sandalwood Pulp', 'Cold-pressed Neem Oil', 'Organic Raw Honey', 'Aloe Gel'],
    familyDemographic: 'Men',
    isFeatured: false
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-01',
    author: 'Miraya S.',
    rating: 5,
    comment: 'The Radiant Elixir Serum is absolutely magical! My dry skin has completely vanished. I pair it with the Silk Wrap Dress which feels incredibly luxurious. This brand understands both beauty and high-end aesthetics!',
    date: '2026-05-18',
    avatarColor: 'bg-rose-100 text-rose-600',
    role: 'Verified Buyer'
  },
  {
    id: 'rev-02',
    author: 'Devendra K.',
    rating: 5,
    comment: 'Great finding clean products that suit both me and my mom. The linen blazer has a fabulous cut and the gold buttons are extremely high value. Fast checkout and lovely pink/peach boxes!',
    date: '2026-06-01',
    avatarColor: 'bg-amber-100 text-amber-600',
    role: 'Style Guide'
  },
  {
    id: 'rev-03',
    author: 'Nisha R.',
    rating: 4,
    comment: 'We booked a virtual style consultation and it was fantastic! The recommendations perfectly paired cosmetics with clothing types. Outstanding customer service and gorgeous floral designs.',
    date: '2026-06-08',
    avatarColor: 'bg-violet-100 text-violet-600',
    role: 'Skincare Lover'
  }
];

export const BEAUTY_SALON_SERVICES = [
  {
    id: 'serv-01',
    name: 'Virtual Skincare Consultation & Facial Scan',
    price: 0,
    duration: '30 Mins',
    description: 'Meet our senior dermatologist online to perform an interactive dermal visual scan and discover your ideal botanical routine.',
    expert: 'Dr. Ananya Ray, Skin Scientist'
  },
  {
    id: 'serv-02',
    name: 'Signature Bride & Wedding Style Portrait',
    price: 120,
    duration: '90 Mins',
    description: 'In-store luxurious fitting of our premium silk collections combined with a customized glowing bio-active makeup draft.',
    expert: 'Lina Sen, Head of Creative Fashion'
  },
  {
    id: 'serv-03',
    name: 'Multi-Generation Boutique Family Styling',
    price: 75,
    duration: '60 Mins',
    description: 'Styling package crafted specifically for kids, parents and grandparents to achieve harmonious apparel matching and skincare prep.',
    expert: 'Vikram Grover, Lead Family Stylist'
  }
];

export const PROMO_CODES = [
  { code: 'VINSHUWELCOME', discount: 15, label: '15% Off Your First Order' },
  { code: 'GLOWSEASON', discount: 10, label: '10% Off Eco-Beauty' },
];
